name: 20x-ORDU-TERMINAL-CANLI ğŸ˜ˆ

on:
  workflow_dispatch:

jobs:
  ates-hatti:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # Bir makine kapanÄ±rsa diÄŸerleri durmasÄ±n
      matrix:
        node: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
    
    steps:
      - name: Terminali Hazirla (Node ${{ matrix.node }})
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: false

      - name: Olumsuzluk Kilidi
        if: always() # tmate kapansa bile makineyi 6 saat acik tutar
        run: sleep 21600
